# Generated by Django 6.0.5 on 2026-06-01 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_userprofile_bio_alter_userprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackreport',
            name='communication_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedbackreport',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='feedbackreport',
            name='generated_by_model',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='feedbackreport',
            name='improvement_plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedbackreport',
            name='report_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedbackreport',
            name='technical_feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
